version: '3'

vars:
  APP_IMAGE: fastapi-react-app
  CONTAINER_NAME: fastapi-react-container

tasks:
  setup/front:
    desc: Build the front
    dir: front
    cmds:
      - npm install
      - npm run build
  setup/backend:
    desc: Build the backend
    dir: backend
    cmds:
      - poetry install
  setup/docker:
    desc: Build the docker image
    cmds:
      - docker-compose up --build -d
  setup:
    desc: Build the front and backend
    deps:
      - setup/front
      - setup/docker
      - setup/backend
  serve/front:
    desc: Serve the front
    dir: front
    cmds:
      - npm run dev
  serve/backend:
    desc: Serve the backend
    dir: backend
    cmds:
      - poetry run python main.py
  serve:
    desc: Serve the front and backend
    deps:
      - serve/front
      - serve/backend

  serve/storybook:
    desc: Serve the storybook
    dir: front
    cmds:
      - npm run storybook

  docker/build:
    desc: Build the docker image
    dir: backend
    cmds:
      - docker build -t {{.APP_IMAGE}} .

  docker/run:
    desc: Run the docker image
    dir: backend
    cmds:
      - docker rm -f {{.CONTAINER_NAME}} || true
      - docker run -d -p 8000:8000 --env-file .env --name {{.CONTAINER_NAME}} {{.APP_IMAGE}}

  docker:
    desc: Build and run the docker image
    deps:
      - docker/build
      - docker/run

  docker/stop:
    desc: Stop the docker image
    dir: backend
    cmds:
      - docker stop {{.CONTAINER_NAME}}