/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI React Backend
 * OpenAPI spec version: 1.0.0
 */

/**
 * ブログ記事作成モデル
 */
export interface BlogPostCreate {
  title: string;
  content: string;
  author: string;
}
