/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI React Backend
 * OpenAPI spec version: 1.0.0
 */
import type { BlogPostUpdateTitle } from './blogPostUpdateTitle';
import type { BlogPostUpdateContent } from './blogPostUpdateContent';
import type { BlogPostUpdateAuthor } from './blogPostUpdateAuthor';

/**
 * ブログ記事更新モデル（すべてのフィールドは省略可能）
 */
export interface BlogPostUpdate {
  title?: BlogPostUpdateTitle;
  content?: BlogPostUpdateContent;
  author?: BlogPostUpdateAuthor;
}
