/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI React Backend
 * OpenAPI spec version: 1.0.0
 */

/**
 * ヘルスチェックレスポンスモデル
 */
export interface HealthCheckResponse {
  status: string;
}
